# Generated by Django 5.2.14 on 2026-05-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_donation_transmittedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
