# Generated by Django 4.2.23 on 2026-09-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_donation_ngo_donation_ngo_name_donation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='rescue_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='rescue_vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='rescued_people_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergency',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='vehicle_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='vehicle_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Dispatch'), ('ngo_found', 'Nearby NGO Found'), ('accepted', 'Accepted'), ('assigned', 'Team Assigned'), ('dispatched', 'Dispatched'), ('on_the_way', 'On The Way'), ('arrived', 'Team Arrived'), ('rescue_in_progress', 'Rescue In Progress'), ('resolved', 'Resolved & Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='RescueAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rescue_team', models.CharField(default='Team Alpha', max_length=100)),
                ('vehicle', models.CharField(default='Rescue Boat RB-04', max_length=100)),
                ('eta', models.IntegerField(default=15)),
                ('status', models.CharField(default='accepted', max_length=30)),
                ('notification_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_assignments', to='api.ngoprofile')),
                ('sos_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.emergency')),
            ],
        ),
    ]
