# Generated by Django 4.2.23 on 2026-09-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emergency_accepted_at_emergency_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='distance_km',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='location_accuracy',
            field=models.FloatField(blank=True, default=10.0, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='vehicle_accuracy',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='vehicle_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(default='Rescue Boat RB-04', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(default=5.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sos_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='api.emergency')),
            ],
        ),
    ]
